#!/bin/bash
# This script converts a CSV file (generated by search_to_csv.sh) into an initial JSON file.
# It adds a 'body': 'pending' placeholder to each email object.

set -e

# --- Configuration & Arguments ---
CSV_FILE=${1}
JSON_FILE=${2}

# --- Pre-flight Checks ---
if [ -z "$CSV_FILE" ] || [ -z "$JSON_FILE" ]; then
    echo "Error: Both an input CSV file and an output JSON file path are required."
    echo "Usage: ./csv_to_json.sh <input_csv_file_path> <output_json_file_path>"
    echo "Example: ./csv_to_json.sh my_emails_metadata.csv my_emails_full_content.json"
    exit 1
fi
if [ ! -f "$CSV_FILE" ]; then
    echo "Error: CSV file not found at '$CSV_FILE'"
    exit 1
fi

echo "Converting '$CSV_FILE' to '$JSON_FILE'..."

python3 -c "
import csv
import json
import sys

csv_file = sys.argv[1]
json_file = sys.argv[2]

data = []
with open(csv_file, 'r', newline='') as infile:
    reader = csv.reader(infile)
    header = [h.strip() for h in next(reader)]

    header_map = {
        'Date': 'date',
        'Message ID': 'id',
        'Thread ID': 'threadId',
        'From': 'from',
        'To': 'to',
        'Subject': 'subject'
    }

    for row in reader:
        if not row:
            continue
        item = {'body': 'pending'}
        for i, value in enumerate(row):
            if i < len(header):
                csv_header = header[i]
                json_key = header_map.get(csv_header, csv_header.replace(' ', ''))
                item[json_key] = value.strip()
        data.append(item)

csv_row_count = len(data)
print(f\"Found \${csv_row_count} data rows in '{csv_file}'.\")

with open(json_file, 'w') as outfile:
    json.dump(data, outfile, indent=2)

json_object_count = len(data)
print(f\"Wrote \${json_object_count} JSON objects to '{json_file}'.\")
" "$CSV_FILE" "$JSON_FILE"

echo "---"
echo "CSV to JSON conversion complete."
echo "  - Initial JSON saved to: $JSON_FILE"
echo "Next step: Run 'update_bodies.sh' to populate the email bodies."
